# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
    - develop

resources:
    - repo: self

stages:
    - stage: Build_And_Deploy
      displayName: Build and Push Docker Image
      jobs:
          - job: Npm_Install
            displayName: Run NPM Install
            pool:
                vmImage: $(vmImageName)
            steps:
                - task: Bash@3
                  displayName: Run npm i
                  inputs:
                      targetType: 'inline'
                      script: 'npm i'
                - task: Bash@3
                  displayName: Run npm run build:qa
                  inputs:
                      targetType: 'inline'
                      script: 'npm run build:staging'
                - task: Docker@2
                  inputs:
                      containerRegistry: 'DigitalOceanRegistry'
                      repository: 'betsy-production/adminpanel-qa'
                      command: 'buildAndPush'
                      Dockerfile: '**/Dockerfile'
                      tags: |
                        $(Build.BuildId)
                        latest
