# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
    - au2

resources:
    -   repo: self

stages:
    -   stage: Build_And_Deploy
        displayName: Build and Push Docker Image
        jobs:
            -   job: Npm_Install
                displayName: Run NPM Install
                pool:
                    vmImage: ubuntu-latest
                steps:
                    -   task: Bash@3
                        displayName: Install pnpm
                        inputs:
                            targetType: 'inline'
                            script: 'wget -qO- https://get.pnpm.io/install.sh | ENV="$HOME/.bashrc" SHELL="$(which bash)" bash -'
                    -   task: Bash@3
                        displayName: Source pnpm
                        inputs:
                            targetType: 'inline'
                            script: 'source /home/vsts/.bashrc'
                    -   task: Bash@3
                        displayName: Run pnpm i
                        inputs:
                            targetType: 'inline'
                            script: 'pnpm i'
                    -   task: Bash@3
                        displayName: Run npm run build:qa
                        inputs:
                            targetType: 'inline'
                            script: 'npm run build:staging'
                    -   task: Docker@2
                        inputs:
                            containerRegistry: 'DigitalOceanRegistry'
                            repository: 'betsy-production/adminpanel-qa'
                            command: 'buildAndPush'
                            Dockerfile: '**/Dockerfile'
                            tags: |
                                $(Build.BuildId)
                                latest
