# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
    - master

resources:
    -   repo: self

variables:
    # Container registry service connection established during pipeline creation
    dockerRegistryServiceConnection: '4d99b72f-99af-4aa6-9be8-c6f43af4d429'
    imageRepository: 'betsypanel'
    containerRegistry: 'BetsyContainerRegistry'
    dockerfilePath: '**/Dockerfile'
    tag: '$(Build.BuildId)'

    # Agent VM image name
    vmImageName: 'ubuntu-latest'

stages:
    -   stage: Build_And_Deploy
        displayName: Build and Push Docker Image
        jobs:
            -   job: Npm_Install
                displayName: Run NPM Install
                pool:
                    vmImage: $(vmImageName)
                steps:
                    -   task: Bash@3
                        displayName: Install pnpm
                        inputs:
                            targetType: 'inline'
                            script: 'wget -qO- https://get.pnpm.io/install.sh | ENV="$HOME/.bashrc" SHELL="$(which bash)" bash -'
                    -   task: Bash@3
                        displayName: Run pnpm i
                        inputs:
                            targetType: 'inline'
                            script: 'pnpm i'
                    -   task: Bash@3
                        displayName: Run npm run build:production
                        inputs:
                            targetType: 'inline'
                            script: 'npm run build'
                    -   task: Docker@2
                        inputs:
                            containerRegistry: 'DigitalOceanRegistry'
                            repository: 'betsy-production/adminpanel'
                            command: 'buildAndPush'
                            Dockerfile: '**/Dockerfile'
                            tags: |
                                $(Build.BuildId)
                                latest
