name: Publish Betsy Web Components

on:
  push:
    branches:
      - master
      - preview

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

permissions:
  contents: write

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.semantic-release.outputs.tag }}
      url: ${{ steps.semantic-release.outputs.url }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@d882d12c64e032187b2edb46d3a0d003b7a43598

      - name: Setup Node with pnpm Cache
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - name: Run pnpm Install
        run: pnpm i

      - name: Semantic Release
        run: |
          pnpm run semantic-release >> semantic-release.log
          echo "url=$(cat semantic-release.log | grep -o 'https.*/tag/.*' | tr -d '\n')" >> $GITHUB_OUTPUT
          echo "tag=$(cat semantic-release.log | grep -o '/tag/.*' | tr -d '/tag/')" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.CI_USER_BETSY }}
          GIT_AUTHOR_NAME: ci-betsy
          GIT_AUTHOR_EMAIL: support@betsybot.xyz
